import { ThemeConfig } from 'antd';

export const designConstants = {
  headerHeight: 56,
  sidebarWidth: 240,
  sidebarCollapsedWidth: 64,
  pagePadding: 24,
  borderRadius: 6,
  cardPadding: 20,
  tableRowHeight: 44,
  colors: {
    bgPage: '#f4f6f9',
    bgCard: '#ffffff',
    borderColor: '#e2e8f0',
    borderLight: '#edf2f7',
    textPrimary: '#0f172a',
    textSecondary: '#64748b',
    textMuted: '#94a3b8',
    primary: '#1677ff',
    success: '#10b981',
    warning: '#f59e0b',
    error: '#ef4444',
    info: '#3b82f6',
  },
};

export const lightTheme: ThemeConfig = {
  token: {
    colorPrimary: '#1677ff',
    colorInfo: '#1677ff',
    colorSuccess: '#10b981',
    colorWarning: '#f59e0b',
    colorError: '#ef4444',
    colorBgBase: '#ffffff',
    colorBgContainer: '#ffffff',
    colorBgElevated: '#ffffff',
    colorBgLayout: '#f4f6f9',
    colorBorder: '#e2e8f0',
    colorBorderSecondary: '#f1f5f9',
    colorText: '#0f172a',
    colorTextSecondary: '#64748b',
    colorTextTertiary: '#94a3b8',
    colorTextQuaternary: '#cbd5e1',
    borderRadius: 6,
    borderRadiusLG: 8,
    borderRadiusSM: 4,
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    fontSize: 13,
    fontSizeHeading1: 24,
    fontSizeHeading2: 20,
    fontSizeHeading3: 16,
    fontSizeHeading4: 14,
    controlHeight: 34,
    controlHeightSM: 28,
    controlHeightLG: 40,
    boxShadow: '0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px -1px rgba(0, 0, 0, 0.05)',
    boxShadowSecondary: '0 4px 6px -1px rgba(0, 0, 0, 0.07), 0 2px 4px -2px rgba(0, 0, 0, 0.05)',
  },
  components: {
    Layout: {
      headerBg: '#ffffff',
      headerHeight: designConstants.headerHeight,
      headerPadding: '0 20px',
      siderBg: '#ffffff',
      bodyBg: '#f4f6f9',
    },
    Menu: {
      itemBg: '#ffffff',
      itemColor: '#475569',
      itemSelectedColor: '#1677ff',
      itemSelectedBg: '#eff6ff',
      itemHoverColor: '#1677ff',
      itemHoverBg: '#f8fafc',
      itemHeight: 38,
      itemBorderRadius: 6,
      subMenuItemBg: '#ffffff',
    },
    Card: {
      headerBg: '#ffffff',
      headerFontSize: 14,
      headerHeight: 48,
    },
    Table: {
      headerBg: '#f8fafc',
      headerColor: '#475569',
      headerSplitColor: 'transparent',
      borderColor: '#edf2f7',
      rowHoverBg: '#f8fafc',
      cellPaddingBlock: 8,
      cellPaddingInline: 12,
      fontSize: 13,
    },
    Button: {
      fontWeight: 500,
      controlHeight: 34,
    },
    Input: {
      activeBorderColor: '#1677ff',
      hoverBorderColor: '#93c5fd',
    },
    Modal: {
      borderRadiusLG: 8,
      headerBg: '#ffffff',
    },
    Drawer: {
      borderRadiusSM: 8,
    },
    Tabs: {
      cardBg: '#f8fafc',
      itemSelectedColor: '#1677ff',
      titleFontSize: 13,
    },
    Tag: {
      borderRadiusSM: 4,
    },
  },
};
